import { readFileSync, writeFileSync } from 'node:fs';

const PAD = 12;          // lề trong viewBox 100
const FLIP_Y = false;    // dataset Hershey này y đã hướng xuống (đỉnh = y nhỏ) → KHÔNG lật
const BOX = 100;

// Thay tay glyph xấu (key rỗng = không override). Toạ độ đã ở hệ viewBox 0..100.
const OVERRIDES = {};

// ----- Nét dấu tiếng Việt (viewBox 0..100), đặt ở vùng trên đỉnh chữ -----
// Tinh chỉnh vị trí ở Task 4 bằng trang preview.
const MARKS = {
  breve:      'M 38 4 Q 50 14 62 4',             // ˘  (Ă) — raised so curve sits above the letter body
  circumflex: 'M 38 14 L 50 4 L 62 14',         // ^  (Â Ê Ô)
  hornO:      'M 70 22 Q 80 18 78 30',          // móc phải trên O (Ơ)
  hornU:      'M 70 22 Q 80 18 78 30',          // móc phải trên U (Ư)
  barD:       'M 14 52 L 38 52',                // gạch ngang thân D (Đ)
};

// Ghép: chữ gốc + (các) nét dấu
const COMPOSITES = {
  'Ă': ['A', 'breve'],
  'Â': ['A', 'circumflex'],
  'Ê': ['E', 'circumflex'],
  'Ô': ['O', 'circumflex'],
  'Ơ': ['O', 'hornO'],
  'Ư': ['U', 'hornU'],
  'Đ': ['D', 'barD'],
};

const raw = JSON.parse(readFileSync(new URL('./vendor/hershey-base.json', import.meta.url)));

// bbox toàn cục
let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
for (const ch of Object.keys(raw)) {
  for (const stroke of raw[ch]) {
    for (const [x, y] of stroke) {
      if (x < minX) minX = x; if (x > maxX) maxX = x;
      if (y < minY) minY = y; if (y > maxY) maxY = y;
    }
  }
}
const w = maxX - minX, h = maxY - minY;
const scale = (BOX - 2 * PAD) / Math.max(w, h);
const offX = (BOX - w * scale) / 2;
const offY = (BOX - h * scale) / 2;

const norm = (x, y) => {
  const nx = offX + (x - minX) * scale;
  let ny = offY + (y - minY) * scale;
  if (FLIP_Y) ny = BOX - ny;
  return [Math.round(nx * 100) / 100, Math.round(ny * 100) / 100];
};

const toPath = (stroke) =>
  'M ' + stroke.map(([x, y]) => { const [a, b] = norm(x, y); return `${a} ${b}`; }).join(' L ');

const base = {};
for (const ch of Object.keys(raw)) {
  base[ch] = OVERRIDES[ch] ?? raw[ch].map(toPath);
}

// composites
const all = { ...base };
for (const [ch, parts] of Object.entries(COMPOSITES)) {
  const baseCh = parts[0];
  const markPaths = parts.slice(1).map((m) => MARKS[m]);
  all[ch] = [...base[baseCh], ...markPaths];
}

const ORDER = [...'0123456789', ...'AĂÂBCDĐEÊGHIKLMNOÔƠPQRSTUƯVXY'];
const body = ORDER
  .filter((c) => all[c])
  .map((c) => `  ${JSON.stringify(c)}: ${JSON.stringify(all[c])},`)
  .join('\n');

const out = `// AUTO-GENERATED by scripts/genLetterStrokes.mjs — do not edit by hand.
// Nguồn: Hershey Roman Simplex (public domain) + dấu tiếng Việt tự vẽ.
export type GlyphStrokes = string[];

export const LETTER_STROKES: Record<string, GlyphStrokes> = {
${body}
};

export function getStrokes(letter: string): GlyphStrokes {
  return LETTER_STROKES[letter] ?? [];
}
`;
writeFileSync(new URL('../src/lib/letterStrokes.ts', import.meta.url), out);
console.log('Wrote src/lib/letterStrokes.ts with', Object.keys(all).length, 'glyphs');
